export const SET_TODOS_ACTION = 'SET_TODOS_ACTION';
export const SET_LOADING_ACTION = 'SET_LOADING_ACTION';
export const SET_ERROR_ACTION = 'SET_ERROR_ACTION';
export const CREATE_TODO_ACTION = 'CREATE_TODO_ACTION';
